# Unless filling for special features, all features should fill for previous forks (starting from Paris) too
stable:
  evm-type: stable
  fill-params: --from=Paris --until=Prague --fill-static-tests --ignore=tests/static/state_tests/stQuadraticComplexityTest

develop:
  evm-type: develop
  fill-params: --from=Paris --until=Osaka --fill-static-tests --ignore=tests/static/state_tests/stQuadraticComplexityTest

benchmark:
  evm-type: benchmark
  fill-params: --fork=Osaka --gas-benchmark-values 1,5,10,30,60,100,150 ./tests/benchmark/compute --maxprocesses=30 --dist=worksteal

benchmark_fast:
  evm-type: benchmark
  fill-params: --fork=Osaka --gas-benchmark-values 100 ./tests/benchmark/compute
  feature_only: true

paris:
  evm-type: develop
  fill-params: >-
    --fork=Paris --fill-static-tests
    --ignore=tests/frontier --ignore=tests/homestead
    --ignore=tests/tangerine_whistle --ignore=tests/byzantium
    --ignore=tests/constantinople --ignore=tests/istanbul
    --ignore=tests/berlin --ignore=tests/london
  feature_only: true

shanghai:
  evm-type: develop
  fill-params: >-
    --fork=Shanghai --fill-static-tests
    --ignore=tests/frontier --ignore=tests/homestead
    --ignore=tests/tangerine_whistle --ignore=tests/byzantium
    --ignore=tests/constantinople --ignore=tests/istanbul
    --ignore=tests/berlin --ignore=tests/london
  feature_only: true

cancun:
  evm-type: develop
  fill-params: >-
    --fork=Cancun --fill-static-tests
    --ignore=tests/frontier --ignore=tests/homestead
    --ignore=tests/tangerine_whistle --ignore=tests/byzantium
    --ignore=tests/constantinople --ignore=tests/istanbul
    --ignore=tests/berlin --ignore=tests/london
  feature_only: true

prague:
  evm-type: develop
  fill-params: >-
    --fork=Prague --fill-static-tests
    --ignore=tests/frontier --ignore=tests/homestead
    --ignore=tests/tangerine_whistle --ignore=tests/byzantium
    --ignore=tests/constantinople --ignore=tests/istanbul
    --ignore=tests/berlin --ignore=tests/london
  feature_only: true

osaka:
  evm-type: develop
  fill-params: >-
    --fork=Osaka --fill-static-tests
    --ignore=tests/frontier --ignore=tests/homestead
    --ignore=tests/tangerine_whistle --ignore=tests/byzantium
    --ignore=tests/constantinople --ignore=tests/istanbul
    --ignore=tests/berlin --ignore=tests/london
  feature_only: true

# bal:
#   evm-type: develop
#   fill-params: >-
#     --fork=Amsterdam --fill-static-tests
#     --ignore=tests/frontier --ignore=tests/homestead
#     --ignore=tests/tangerine_whistle --ignore=tests/byzantium
#     --ignore=tests/constantinople --ignore=tests/istanbul
#     --ignore=tests/berlin --ignore=tests/london
#   feature_only: true
