# Unless filling for special features, all features should fill for previous forks (starting from Paris) too
mainnet:
  evm-type: eels
  fill-params: --from=Paris --until=Osaka

benchmark:
  evm-type: benchmark
  fill-params: --fork=Osaka --gas-benchmark-values 1,5,10,30,60,100,150 ./tests/benchmark/compute --maxprocesses=30 --dist=worksteal
  feature_only: true

benchmark_fast:
  evm-type: benchmark
  fill-params: --fork=Osaka --gas-benchmark-values 100 ./tests/benchmark/compute
  feature_only: true

merge:
  evm-type: eels
  fill-params: --fork=Paris
  feature_only: true

shapella:
  evm-type: eels
  fill-params: --fork=Shanghai
  feature_only: true

dencun:
  evm-type: eels
  fill-params: --fork=Cancun
  feature_only: true

pectra:
  evm-type: eels
  fill-params: --fork=Prague
  feature_only: true

fusaka:
  evm-type: eels
  fill-params: --fork=Osaka
  feature_only: true

bal:
  evm-type: eels
  fill-params: --fork=Amsterdam
  feature_only: true

