name: Setup Environment
description: Common setup for Ethereum Spec jobs
runs:
  using: "composite"
  steps:
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: "1.69.0"
        override: true

    - name: Ensure build deps (idempotent)
      shell: bash
      run: |
        set -euo pipefail
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential pkg-config

    - name: Install tox + helpers
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install 'tox>=4.11,<5' requests

    - name: Download Geth and add to PATH
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p "$GITHUB_WORKSPACE/bin"
        python "$GITHUB_WORKSPACE/scripts/download_geth_linux.py" --dir "$GITHUB_WORKSPACE/bin"
        echo "$GITHUB_WORKSPACE/bin" >> "$GITHUB_PATH"

