name: Load Cached Docker Images
description: Load Docker images from cache

inputs:
  cache-key-prefix:
    description: "Prefix for the cache key"
    required: false
    default: "docker-images"

runs:
  using: "composite"
  steps:
    - name: Get week number
      id: week
      shell: bash
      run: echo "num=$(date +%U)" >> $GITHUB_OUTPUT

    - name: Restore Docker image cache
      uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: /tmp/docker-images
        key: ${{ inputs.cache-key-prefix }}-week${{ steps.week.outputs.num }}-${{ hashFiles('.github/actions/cache-docker-images/action.yaml', 'execution-specs/.github/actions/cache-docker-images/action.yaml') }}

    - name: Load cached Docker images
      shell: bash
      run: |
        if [ -d /tmp/docker-images ]; then
          for file in /tmp/docker-images/*.tar.gz; do
            if [ -f "$file" ]; then
              echo "Loading $file..."
              gunzip -c "$file" | docker load
            fi
          done
        else
          echo "::error::No cached images found - cache may not exist yet. Run the cache-docker-images action first."
          exit 1
        fi
