name: render

on:
  push:
    branches:
      - master
      - mainnet
      - 'forks/**'
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: "Build Documentation"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: "3.11"

      - name: Install Tox
        run: pip install tox

      - name: Build Documentation
        run: |
          tox -e doc
          touch .tox/docs/.nojekyll

      - name: Upload Pages Artifact
        id: artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b
        with:
          path: .tox/docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: "Deploy Documentation"
    if: ${{ github.event_name == 'push' && github.ref_name == github.event.repository.default_branch }}

    permissions:
      pages: write
      id-token: write
      actions: read

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e
