name: Hive - Gnosis (Fusaka)

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at 00:00 UTC
  workflow_dispatch:
    inputs:
      client:
        type: string
        default: '"go-ethereum-gnosis","reth-gnosis","nethermind-gnosis","erigon-gnosis"'
        description: Comma-separated list of clients to test e.g. go-ethereum-gnosis, reth-gnosis, nethermind-gnosis, erigon-gnosis
      simulator:
        type: string
        default: >-
          "gnosis/eels/consume-engine",
          "gnosis/eels/consume-rlp",
          "gnosis/eels/consume-sync"
        description: >-
          Comma-separated list of simulators to test
          e.g. gnosis/eels/consume-engine, gnosis/eels/consume-rlp, gnosis/eels/consume-sync
      hive_version:
        type: string
        default: gnosischain/hive@master
        description: GitHub repository and tag for hive (repo@tag)
      client_source:
        type: choice
        description: >-
          How client images should be sourced.
          'git' will use the github repo and tag (See client_repos).
          'docker' will use the docker registry and tag (See client_images).
        options:
          - docker
          - git
      client_repos:
        type: string
        default: |
          {
            "geth": "gnosischain/go-ethereum@v1.16.8-gc",
            "reth": "gnosischain/reth_gnosis@master",
            "nethermind": "NethermindEth/nethermind@master",
            "erigon": "erigontech/erigon@main"
          }
        description: 'JSON object containing client versions in format {"client": "repo@tag", ...}'
      client_images:
        type: string
        default: |
          {
            "geth": "ghcr.io/gnosischain/geth:v1.16.8-gc",
            "reth": "ghcr.io/gnosischain/reth_gnosis:master",
            "nethermind": "nethermind/nethermind:1.36.0",
            "erigon": "erigontech/erigon:latest"
          }
        description: 'JSON object containing client docker images in format {"client": "registry:tag", ...}'

env:
  GOPROXY: "${{ vars.GOPROXY }}"
  GCS_BUCKET: gnosis-hive-ui-staging
  GCS_PATH: fusaka
  GCS_PUBLIC_URL: https://storage.googleapis.com/gnosis-hive-ui-staging/fusaka
  INSTALL_RCLONE_VERSION: v1.68.2
  EELS_BUILD_ARG_FIXTURES: https://github.com/gnosischain/execution-spec-tests/releases/download/v0.1.0/fixtures_osaka.tar.gz
  EELS_BUILD_ARG_BRANCH: forks/amsterdam
  # Flags used for all simulators
  GLOBAL_EXTRA_FLAGS: >-
    --client.checktimelimit=300s
    --docker.buildoutput
  # Flags used for the gnosis/eels/consume-engine simulator
  EELS_ENGINE_FLAGS: >-
    --sim.parallelism=6
    --sim.buildarg fixtures=${EELS_BUILD_ARG_FIXTURES}
    --sim.buildarg branch=${EELS_BUILD_ARG_BRANCH}
    --sim.loglevel=3
    --sim.limit=.*Osaka.*
  # Flags used for the gnosis/eels/consume-rlp simulator
  EELS_RLP_FLAGS: >-
    --sim.parallelism=6
    --sim.buildarg fixtures=${EELS_BUILD_ARG_FIXTURES}
    --sim.buildarg branch=${EELS_BUILD_ARG_BRANCH}
    --sim.loglevel=3
    --sim.limit=.*Osaka.*

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      hive_repo: >-
        ${{
          steps.client_config_schedule.outputs.hive_repo ||
          steps.client_config_dispatch.outputs.hive_repo
        }}
      hive_tag: >-
        ${{
          steps.client_config_schedule.outputs.hive_tag ||
          steps.client_config_dispatch.outputs.hive_tag
        }}
      client_config: >-
        ${{
          steps.client_config_schedule.outputs.client_config ||
          steps.client_config_dispatch.outputs.client_config
        }}
    steps:
      - uses: gnosischain/hive-github-action/helpers/client-config@9f65ec1bd266757a681c38d38b7fc9e341b08f0a
        if: github.event_name == 'schedule'
        name: 'Client config: schedule'
        id: client_config_schedule
        with:
          client_source: 'git'
          hive_version: 'gnosischain/hive@master'
          goproxy: ${{ env.GOPROXY }}

      - uses: gnosischain/hive-github-action/helpers/client-config@9f65ec1bd266757a681c38d38b7fc9e341b08f0a
        if: github.event_name == 'workflow_dispatch'
        name: 'Client config: workflow_dispatch'
        id: client_config_dispatch
        with:
          client_repos: ${{ inputs.client_repos }}
          client_images: ${{ inputs.client_images }}
          client_source: ${{ inputs.client_source }}
          hive_version: ${{ inputs.hive_version }}
          goproxy: ${{ env.GOPROXY }}

  test:
    timeout-minutes: 2160
    needs: prepare
    if: >-
      github.event_name == 'schedule' ||
      !contains(inputs.simulator, 'consume-sync') ||
      (contains(inputs.simulator, 'consume-engine') || contains(inputs.simulator, 'consume-rlp'))
    runs-on: ubuntu-latest
    concurrency:
      group: >-
        ${{ github.head_ref || inputs }}-${{ matrix.client }}-${{ matrix.simulator }}
    strategy:
      fail-fast: false
      matrix:
        client: >-
          ${{ fromJSON(format('[{0}]', inputs.client || '
            "go-ethereum-gnosis",
            "reth-gnosis",
            "nethermind-gnosis",
            "erigon-gnosis"
          '))}}
        simulator: >-
          ${{ fromJSON(format('[{0}]', inputs.simulator || '
            "gnosis/eels/consume-engine",
            "gnosis/eels/consume-rlp"
          '))}}
        exclude:
          - simulator: 'gnosis/eels/consume-sync'
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: gnosischain/hive-github-action@1d88652e508626aaefa085d830ea05f422384300
        with:
          hive_repository: ${{ needs.prepare.outputs.hive_repo }}
          hive_version: ${{ needs.prepare.outputs.hive_tag }}
          client: ${{ matrix.client }}
          simulator: ${{ matrix.simulator }}
          client_config: ${{ needs.prepare.outputs.client_config }}
          extra_flags: >-
            ${{ env.GLOBAL_EXTRA_FLAGS }}
            ${{ matrix.simulator == 'gnosis/eels/consume-engine' && env.EELS_ENGINE_FLAGS || '' }}
            ${{ matrix.simulator == 'gnosis/eels/consume-rlp' && env.EELS_RLP_FLAGS || '' }}
          gcs_upload: true
          gcs_bucket: ${{ env.GCS_BUCKET }}
          gcs_path: ${{ env.GCS_PATH }}
          gcs_public_url: ${{ env.GCS_PUBLIC_URL }}
          rclone_config: ${{ secrets.HIVE_RCLONE_CONFIG }}
          rclone_version: ${{ env.INSTALL_RCLONE_VERSION }}
          workflow_artifact_upload: true
          website_upload: true

  test-consume-sync-matrix:
    timeout-minutes: 2160
    needs: prepare
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.head_ref || inputs }}-sync-matrix
    if: contains(inputs.simulator || 'gnosis/eels/consume-sync', 'gnosis/eels/consume-sync')
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: gnosischain/hive-github-action@1d88652e508626aaefa085d830ea05f422384300
        with:
          hive_repository: ${{ needs.prepare.outputs.hive_repo }}
          hive_version: ${{ needs.prepare.outputs.hive_tag }}
          client: >-
            ${{
              inputs.client || '"go-ethereum-gnosis","reth-gnosis","nethermind-gnosis","erigon-gnosis"'
            }}
          simulator: 'gnosis/eels/consume-sync'
          client_config: ${{ needs.prepare.outputs.client_config }}
          extra_flags: >-
            ${{ env.GLOBAL_EXTRA_FLAGS }}
          gcs_upload: true
          gcs_bucket: ${{ env.GCS_BUCKET }}
          gcs_path: ${{ env.GCS_PATH }}
          gcs_public_url: ${{ env.GCS_PUBLIC_URL }}
          rclone_config: ${{ secrets.HIVE_RCLONE_CONFIG }}
          rclone_version: ${{ env.INSTALL_RCLONE_VERSION }}
          workflow_artifact_upload: true
          website_upload: true
